// Code generated by "stringer -type opcode enum.go"; DO NOT EDIT

package regexp

import "fmt"

const _opcode_name = "opAcceptopAssertopCharopCharClassopDotopDotNLopNotCharClassopNopopSaveopSplit"

var _opcode_index = [...]uint8{0, 8, 16, 22, 33, 38, 45, 59, 64, 70, 77}

func (i opcode) String() string {
	if i < 0 || i >= opcode(len(_opcode_index)-1) {
		return fmt.Sprintf("opcode(%d)", i)
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
